version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8081:8080"
      - "9009:9009"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8080:8080"

